version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: franciscocfreire/fiap-docker-nginx:0.0.1
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
